spring:
  profiles:
    default: "dev"
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:

      ddl-auto: create-drop
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  sql:
    init:
      encoding: UTF-8
server:
  error:
    include-message: always
management:
  endpoints:
    web:
      base-path: "/private/actuator"
      exposure:
        include: [ info ]
  info:
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
jvezolles:
  api:
    user:
      get-all: "/public/user"
      get: "/public/user/{username}"
      create: "/public/user"
      update: "/public/user"
      replace: "/public/user/{username}"
      delete: "/public/user/{username}"
